---
- name: Remove existing SOLR_HEAP configuration.
  lineinfile:
    dest: "{{ solr_config_file }}"
    regexp: "^SOLR_HEAP"
    state: absent
  notify: restart solr

- name: Apply Solr configuration changes.
  lineinfile:
    dest: "{{ solr_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^.?SOLR_JAVA_MEM="
      line: 'SOLR_JAVA_MEM="-Xms{{ solr_xms }} -Xmx{{ solr_xmx }}"'
    - regexp: "^SOLR_PORT="
      line: 'SOLR_PORT="{{ solr_port }}"'
    - regexp: "^.?SOLR_TIMEZONE="
      line: 'SOLR_TIMEZONE="{{ solr_timezone }}"'
    - regexp: "^.?SOLR_HOST=.*$"
      line: 'SOLR_HOST="{{ ansible_default_ipv4.address }}"'
    - regexp: "^.?ZK_HOST=\"\""
      line: 'ZK_HOST="{% for server in zookeeper_hosts %}{% if server.host is defined %}{{server.host}}:{{zookeeper_client_port}}{% else %}{{server}}:{{zookeeper_client_port}}{% endif %}{%if loop.index != loop.length %},{% endif %}{% endfor %}"'
  notify: 
    - restart solr
    - reload systemctl
