---
- name: restart solr
  service:
    name: "{{ solr_service_name }}"
    state: restarted
    sleep: 5
  when: solr_restart_handler_enabled

- name: reload systemctl
  shell: systemctl daemon-reload